//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrankenDenHaasWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public int AdresId { get; set; }
        public string Land { get; set; }
        public string Provincie { get; set; }
        public string Stad { get; set; }
        public string Postcode { get; set; }
        public string Straatnaam { get; set; }
        public string Nummer_Bus { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
