//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrankenDenHaasWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.Adresses = new HashSet<Adress>();
            this.Debitcards = new HashSet<Debitcard>();
            this.Customers = new HashSet<Customer>();
            this.Sessions = new HashSet<Session>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string Discriminator { get; set; }
        public string Email { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public string Telefoon { get; set; }
        public string BTW_nummer { get; set; }
        public Nullable<bool> IsZakelijk { get; set; }
        public string TaalId { get; set; }
        public Nullable<System.DateTime> GeboorteDatum { get; set; }
    
        public virtual ICollection<Adress> Adresses { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<Debitcard> Debitcards { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
