//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrankenDenHaasWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debitcard
    {
        public Debitcard()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int BetaalkaartId { get; set; }
        public string Id { get; set; }
        public string KaartNaam { get; set; }
        public string Kaartnummer { get; set; }
        public System.DateTime DatumGeldigTot { get; set; }
        public Nullable<bool> Primairekaart { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
