//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrankenDenHaasWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Products
    {
        public int BestelId { get; set; }
        public int ProductId { get; set; }
        public int Aantal { get; set; }
        public decimal Prijs_Item { get; set; }
        public decimal Subtotaal { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
