//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrankenDenHaasWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Orders_Products = new HashSet<Orders_Products>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int BestelId { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> DatumVanBestelling { get; set; }
        public decimal Totaalprijs { get; set; }
        public Nullable<bool> IsBetaald { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Orders_Products> Orders_Products { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
