//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrankenDenHaasWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Multimedias = new HashSet<Multimedia>();
            this.Orders_Products = new HashSet<Orders_Products>();
        }
    
        public int ProductId { get; set; }
        public string Productnaam { get; set; }
        public decimal Prijs { get; set; }
        public string Beschrijving { get; set; }
        public int CategorieId { get; set; }
        public Nullable<double> AlcoholPercentage___ { get; set; }
        public double Inhoud_cl_ { get; set; }
        public int ProducentId { get; set; }
        public string VerkochtPer { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Multimedia> Multimedias { get; set; }
        public virtual ICollection<Orders_Products> Orders_Products { get; set; }
        public virtual Producer Producer { get; set; }
    }
}
